import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import Nabvar from './components/navbar/Nabvar'

import ToasterProvider from './components/providers/ToasterProvider'
import RegisterModal from './components/modals/RegisterModal'
import LoginModal from './components/modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import Categories from './components/Categories'
import RentModal from './components/modals/RentModal'




// const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['200', '400'] })

export const metadata: Metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToasterProvider />
        <Nabvar currentUser={currentUser} />
        <RegisterModal />
        <LoginModal />
        <RentModal />
        <Categories />
        {children}</body>
    </html>
  )
}
